# Generated by Django 5.0.6 on 2024-06-17 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0002_rename_musclegroup_exercise_delete_cardioexercise"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Exercise",
            new_name="Subject",
        ),
    ]
