# Generated by Django 4.2.13 on 2024-06-18 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0006_activity_is_rest"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={"ordering": ["date"]},
        ),
    ]
