# Generated by Django 4.2.13 on 2024-06-18 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0007_alter_activity_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={},
        ),
    ]
